name: sikum
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  go_router: ^7.0.1
  crypto: ^3.0.6
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0
  cloud_functions: ^5.5.0
  firebase_auth: ^5.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
