// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp6C959iYfRp3BWhr-cdwm5PYsrOSEBJI',
    appId: '1:529924557091:web:dc8865694ceafe26bb2496',
    messagingSenderId: '529924557091',
    projectId: 'sikum-91e28',
    authDomain: 'sikum-91e28.firebaseapp.com',
    storageBucket: 'sikum-91e28.firebasestorage.app',
    measurementId: 'G-WT5PK19RGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3wrx3KsSRuZHkyW65a4a0F2FNNAQCll0',
    appId: '1:529924557091:android:07e794bd800e4dbdbb2496',
    messagingSenderId: '529924557091',
    projectId: 'sikum-91e28',
    storageBucket: 'sikum-91e28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWI-98goAB11kFY7slcqbxwlQ7xye_xWg',
    appId: '1:529924557091:ios:9abafa49ff73bb1fbb2496',
    messagingSenderId: '529924557091',
    projectId: 'sikum-91e28',
    storageBucket: 'sikum-91e28.firebasestorage.app',
    iosBundleId: 'com.example.sikum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWI-98goAB11kFY7slcqbxwlQ7xye_xWg',
    appId: '1:529924557091:ios:9abafa49ff73bb1fbb2496',
    messagingSenderId: '529924557091',
    projectId: 'sikum-91e28',
    storageBucket: 'sikum-91e28.firebasestorage.app',
    iosBundleId: 'com.example.sikum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp6C959iYfRp3BWhr-cdwm5PYsrOSEBJI',
    appId: '1:529924557091:web:caf662ede8535b79bb2496',
    messagingSenderId: '529924557091',
    projectId: 'sikum-91e28',
    authDomain: 'sikum-91e28.firebaseapp.com',
    storageBucket: 'sikum-91e28.firebasestorage.app',
    measurementId: 'G-VHNKH2F4FQ',
  );
}
